[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "nodejs", "playwright"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "playwright install --with-deps"
]

[start]
cmd = "python app.py"
